version: '3.2'

services:
  mongodb:
    image: mongo:latest
    ports:
      - '8216:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=sonth
      - MONGO_INITDB_ROOT_PASSWORD=sonthdz
    command: mongod
    volumes:
      - /media/NewHDD/erp/mongo-son:/data/db
    networks:
      - sondz
    restart: always

  appserver:
    image: "server:latest"
    ports:
      - '8200:3000'
    environment:
      PORT: '3000'
      TZ: 'Asia/Bangkok'
      DB_SERVERS: 'mongodb:27017'
      DB_USER: 'sonth'
      DB_PASS: 'sonthdz'
      CLOUD_NAME: "dxjrsffeo"
      API_KEY_CLOUDINARY: "145441169219581"
      API_SECRET_CLOUDINARY: "KQ8npWR4yLqOfK9cLQieU6W_bMs"

    networks:
      - sondz
    restart: always
  web-sonth:
    image: "web-sonth:latest"
    ports:
      - '8201:3000'
    environment:
      PORT: '3000'
      TZ: 'Asia/Bangkok'
    restart: always
  cms:
    image: "cms:latest"
    ports:
      - '8202:3000'
    environment:
      PORT: '3000'
      TZ: 'Asia/Bangkok'
    restart: always
networks:
  sondz:
    driver: bridge
